# Generated by Django 5.1.3 on 2024-11-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tipo',
            field=models.CharField(choices=[('M1', 'Mecanica - Motor/Cambio'), ('M2', 'Mecanica - Outros'), ('E1', 'Eletrica - Injecao Eletronica'), ('E2', 'Eletrica - Outros')], default='E1', max_length=2),
        ),
    ]
