# Generated by Django 5.1.3 on 2024-11-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_post_aprovado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=11)),
                ('placa', models.CharField(max_length=7)),
                ('modelo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
